// <auto-generated />
using System;
using Korp.Estoque.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Korp.Estoque.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(EstoqueDbContext))]
    [Migration("20260821214436_BaixasProcessadas")]
    partial class BaixasProcessadas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Korp.Estoque.Application.Baixas.BaixaProcessada", b =>
                {
                    b.Property<Guid>("NotaFiscalId")
                        .HasColumnType("uuid")
                        .HasColumnName("nota_fiscal_id");

                    b.Property<DateTimeOffset>("ProcessadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processada_em");

                    b.Property<string>("RespostaJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resposta_json");

                    b.HasKey("NotaFiscalId");

                    b.ToTable("baixas_processadas", "public");
                });

            modelBuilder.Entity("Korp.Estoque.Application.Produtos.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<int>("Saldo")
                        .HasColumnType("integer")
                        .HasColumnName("saldo");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_produtos_codigo");

                    b.ToTable("produtos", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
