@host = http://localhost:5002
@estoque = http://localhost:5001
@produtoA = 01a0267d-11ed-70c2-a4dc-4fbed8742046

### Criar Nota Fiscal
POST {{host}}/api/notas-fiscais
Content-Type: application/json

{
  "itens": [
    {
      "produtoId": "{{produtoA}}",
      "quantidade": 1
    }
  ]
}

### 1. Criar produto novo com saldo
# @name criarProduto
POST {{estoque}}/api/produtos
Content-Type: application/json

{
  "codigo": "CONC-01",
  "descricao": "Produto para teste de concorrencia",
  "saldo": 1
}

### 2. Nota A pedindo 1 unidade (Execute e guarde o id)
POST {{host}}/api/notas-fiscais
Content-Type: application/json

{
  "itens": [
    {
      "produtoId": "{{criarProduto.response.body.id}}",
      "quantidade": 1
    }
  ]
}

### 3. Nota B pedindo 1 unidade (Execute e guarde o id)
POST {{host}}/api/notas-fiscais
Content-Type: application/json

{
  "itens": [
    {
      "produtoId": "{{criarProduto.response.body.id}}",
      "quantidade": 1
    }
  ]
}

### 4. Confirmar saldo inicial = 1
GET {{estoque}}/api/produtos/{{criarProduto.response.body.id}}