<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Korp.Faturamento.Application\Korp.Faturamento.Application.csproj" />
    <ProjectReference Include="..\Korp.Faturamento.Infrastructure\Korp.Faturamento.Infrastructure.csproj" />
  </ItemGroup>

</Project>
